openapi: 3.0.3
info:
  title: Work flex - OpenAPI 3.0
  contact:
    email: lmnhut1612@gmail.com
  version: 1.0.1
servers:
  - url: http://localhost:3000/api
tags:
  - name: category
    description: Everything about your Categories
  - name: skill
    description: Everything about your Skills
  - name: user
    description: Operations about user
paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: Cho phép user đăng nhập hệ thống
      description: "Đăng nhập với tài khoản và mật khẩu vào hệ thống"
      operationId: loginUser
      requestBody:
        description: Update an existent user in the store
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthLogin"
      responses:
        "200":
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - type: object
                    properties:
                      metadata:
                        type: object
                        properties:
                          accessToken:
                            type: string
                            example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNmZGU4NThiLTk4MmMtNDM3Yy1hY2YyLTI3NGE3NzMwNmEwOSIsImVtYWlsIjoicXV5bGhAZ21haWwuY29tIiwiaWF0IjoxNzI2MDEzMzY4LCJleHAiOjE3MjYxODYxNjh9.hiA5Kpqb3SSCNe770Lh3263xE6CBW2eaLJxZx3wGPDk
                          refreshToken:
                            type: string
                            example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNmZGU4NThiLTk4MmMtNDM3Yy1hY2YyLTI3NGE3NzMwNmEwOSIsImVtYWlsIjoicXV5bGhAZ21haWwuY29tIiwiaWF0IjoxNzI2MDEzMzY4LCJleHAiOjE3MjYxODYxNjh9.sQelN-zVihKwJvwy3pVyggl5pBAD_KpGmxSgbYT7_EE
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /user/change-avatar:
    patch:
      tags:
        - user
      summary: Cho phép user thay đổi ảnh đại diện
      operationId: changeAvatar
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: x-client-id
          schema:
            type: string
            format: uuid
          required: true
          description: Client ID for authentication
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
      responses:
        "200":
          description: Cập nhật ảnh đại diện thành công!
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - type: object
                    properties:
                      metadata:
                        type: object
                        properties:
                          avatarUrl:
                            type: string
                            example: https://res.cloudinary.com/workflex/image/upload/v1726837084/avatar/cfde858b-982c-437c-acf2-274a77306a09/avatar.jpg
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /category:
    get:
      tags:
        - category
      summary: Lấy thông tin tất cả lĩnh vực
      description: Lấy thông tin tất cả các lĩnh vực dành cho Admin
      operationId: getAllCategories
      responses:
        "200":
          description: Thành công
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - type: object
                    properties:
                      metadata:
                        type: object
                        properties:
                          length:
                            type: integer
                            example: 1
                          categories:
                            type: array
                            items:
                              $ref: "#/components/schemas/Category"
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    post:
      tags:
        - category
      summary: Thêm mới lĩnh vực
      description: Thêm mới lĩnh vực vào database
      security:
        - bearerAuth: []
      operationId: addCategory
      parameters:
        - in: header
          name: x-client-id
          schema:
            type: string
            format: uuid
          required: true
          description: Client ID for authentication
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  example: Quản lý dự án
          application/x-www-form-urlencoded:
            schema:
              properties:
                name:
                  type: string
                  example: Quản lý dự án
        required: true
      responses:
        "200":
          description: Thêm mới thành công
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
            application/xml:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /category/{id}:
    put:
      tags:
        - category
      summary: Cập nhật lĩnh vực đang tồn tại.
      description: Cập nhật lĩnh vực bằng id
      operationId: updateCategory
      parameters:
        - name: id
          in: path
          description: id của lĩnh vực cần cập nhật
          required: true
          schema:
            type: string
            format: uuid
            default: 2c8ffa97-cfce-4daa-b50c-feff239095fe
      requestBody:
        description: Update an existent cateogry in the store
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  default: Trí tuệ nhân tạo - AI
        required: true
      responses:
        "201":
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - type: object
                    properties:
                      metadata:
                        $ref: "#/components/schemas/Category"
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: NotFound
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /permission:
    post:
      tags:
        - permission
      summary: Thêm mới phân quyền
      description: Thêm phân quyền mới vào database
      security:
        - bearerAuth: []
      operationId: addPermission
      parameters:
        - in: header
          name: x-client-id
          schema:
            type: string
            format: uuid
          required: true
          description: Client ID for authentication
      requestBody:
        content:
          application/json:
            schema:
              properties:
                title:
                  type: string
                  example: add-permission
                description:
                  type: string
                  example: Cho phép thêm phân quyền cho hệ thống
        required: true
      responses:
        "201":
          description: Thêm mới thành công
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - type: object
                    properties:
                      metadata:
                        type: object
                        properties:
                          permission:
                            type: object
                            properties:
                              title:
                                type: string
                                example: add-permission
                              description:
                                type: string
                                example: Cho phép thêm phân quyền cho hệ thống
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: UnprocessableEntity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /role/add-permission:
    post:
      tags:
        - role
      summary: Thêm mới quyền cho vai trò
      description: Thêm phân quyền mới cho role trên hệ thống
      security:
        - bearerAuth: []
      operationId: roleAddPermission
      parameters:
        - in: header
          name: x-client-id
          schema:
            type: string
            format: uuid
          required: true
          description: Client ID for authentication
      requestBody:
        content:
          application/json:
            schema:
              properties:
                roleId:
                  type: string
                  format: uuid
                  example: 72d2ce71-b87e-4976-8cb6-b47f2afa5fce
                permissionId:
                  type: string
                  format: uuid
                  example: 9a3d6ee2-945f-4b2a-b85f-eb07f45040be
        required: true
      responses:
        "200":
          description: Thêm quyền cho vai trò thành công!
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - type: object
                    properties:
                      metadata:
                        type: object
                        properties:
                          role:
                            type: object
                            properties:
                              title:
                                type: string
                                example: add-permission
                              description:
                                type: string
                                example: Cho phép thêm phân quyền cho hệ thống
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: UnprocessableEntity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    AuthLogin:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          example: "nhut@dev"
    Category:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: "Phát triển web"
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      xml:
        name: category
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          description: Thông báo về kết quả của operation
        status:
          type: integer
          example: 2xx
          description: Mã trạng thái HTTP
    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          description: Trạng thái của response (thường là "fail")
        message:
          type: string
          description: Thông báo lỗi chi tiết

  # requestBodies:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: x-api-key
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
